steps:
  # Build the backend (n8n)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.backend', '-t', 'gcr.io/agora-pro-platform/agora-backend:latest', '.']
  
  # Push backend image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/agora-pro-platform/agora-backend:latest']

images:
  - 'gcr.io/agora-pro-platform/agora-backend:latest' 