steps:
  # Build the React app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agora-frontend', '-f', 'Dockerfile.frontend', '.']
    
  # Build the backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/agora-backend', '-f', 'Dockerfile.backend', '.']
    
  # Push images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agora-frontend']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/agora-backend']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agora-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agora-frontend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'agora-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/agora-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5678'
      - '--set-env-vars'
      - 'DATABASE_URL=postgresql://user:pass@host:5432/agora_db,REDIS_URL=redis://host:6379'

images:
  - 'gcr.io/$PROJECT_ID/agora-frontend'
  - 'gcr.io/$PROJECT_ID/agora-backend' 