apiVersion: v1
kind: Secret
metadata:
  name: n8n-secrets
  namespace: agora-pro
type: Opaque
data:
  password: YWRtaW5wYXNzd29yZA==  # adminpassword (base64)
  encryption-key: YWdvcmEtZW5jcnlwdGlvbi1rZXk=  # agora-encryption-key (base64)
  db-user: bjhudXNlcg==  # n8nuser (base64)
  db-password: bjhucGFzc3dvcmQ=  # n8npassword (base64)
  redis-password: cmVkaXNwYXNzd29yZA==  # redispassword (base64)
  gemini-api-key: Z2VtaW5pLWFwaS1rZXk=  # gemini-api-key (base64)
---
apiVersion: v1
kind: Secret
metadata:
  name: n8n-registry-secret
  namespace: agora-pro
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjoge30KfQ==  # {"auths": {}} (base64) 